/* SPDX-License-Identifier: ((GPL-2.0 WITH Linux-syscall-note) OR BSD-3-Clause) */
/* Do not edit directly, auto-generated from: */
/*	Documentation/netlink/specs/nfsd_server.yaml */
/* YNL-GEN uapi header */

#ifndef _UAPI_LINUX_NFSD_SERVER_H
#define _UAPI_LINUX_NFSD_SERVER_H

#define NFSD_SERVER_FAMILY_NAME		"nfsd_server"
#define NFSD_SERVER_FAMILY_VERSION	1

enum nfsd_rpc_status_comp_attr {
	NFSD_ATTR_RPC_STATUS_COMP_UNSPEC,
	NFSD_ATTR_RPC_STATUS_COMP_OP,

	__NFSD_ATTR_RPC_STATUS_COMP_MAX,
	NFSD_ATTR_RPC_STATUS_COMP_MAX = (__NFSD_ATTR_RPC_STATUS_COMP_MAX - 1)
};

enum nfsd_rpc_status_attr {
	NFSD_ATTR_RPC_STATUS_UNSPEC,
	NFSD_ATTR_RPC_STATUS_XID,
	NFSD_ATTR_RPC_STATUS_FLAGS,
	NFSD_ATTR_RPC_STATUS_PROG,
	NFSD_ATTR_RPC_STATUS_VERSION,
	NFSD_ATTR_RPC_STATUS_PROC,
	NFSD_ATTR_RPC_STATUS_SERVICE_TIME,
	NFSD_ATTR_RPC_STATUS_PAD,
	NFSD_ATTR_RPC_STATUS_SADDR4,
	NFSD_ATTR_RPC_STATUS_DADDR4,
	NFSD_ATTR_RPC_STATUS_SADDR6,
	NFSD_ATTR_RPC_STATUS_DADDR6,
	NFSD_ATTR_RPC_STATUS_SPORT,
	NFSD_ATTR_RPC_STATUS_DPORT,
	NFSD_ATTR_RPC_STATUS_COMPOND_OP,

	__NFSD_ATTR_RPC_STATUS_MAX,
	NFSD_ATTR_RPC_STATUS_MAX = (__NFSD_ATTR_RPC_STATUS_MAX - 1)
};

enum nfsd_commands {
	NFSD_CMD_UNSPEC,
	NFSD_CMD_RPC_STATUS_GET,

	__NFSD_CMD_MAX,
	NFSD_CMD_MAX = (__NFSD_CMD_MAX - 1)
};

#endif /* _UAPI_LINUX_NFSD_SERVER_H */
