// SPDX-License-Identifier: GPL-2.0
// Generated by xdrgen. Manual edits will be lost.
// XDR specification file: ../../Documentation/sunrpc/xdr/nfs4_1.x
// XDR specification modification time: Wed Sep 24 09:39:12 2025

#include <linux/sunrpc/svc.h>

#include "nfs4xdr_gen.h"

static bool __maybe_unused
xdrgen_decode_int32_t(struct xdr_stream *xdr, int32_t *ptr)
{
	return xdrgen_decode_int(xdr, ptr);
};

static bool __maybe_unused
xdrgen_decode_uint32_t(struct xdr_stream *xdr, uint32_t *ptr)
{
	return xdrgen_decode_unsigned_int(xdr, ptr);
};

static bool __maybe_unused
xdrgen_decode_int64_t(struct xdr_stream *xdr, int64_t *ptr)
{
	return xdrgen_decode_hyper(xdr, ptr);
};

static bool __maybe_unused
xdrgen_decode_uint64_t(struct xdr_stream *xdr, uint64_t *ptr)
{
	return xdrgen_decode_unsigned_hyper(xdr, ptr);
};

static bool __maybe_unused
xdrgen_decode_nfsstat4(struct xdr_stream *xdr, nfsstat4 *ptr)
{
	u32 val;

	if (xdr_stream_decode_u32(xdr, &val) < 0)
		return false;
	*ptr = val;
	return true;
}

static bool __maybe_unused
xdrgen_decode_attrlist4(struct xdr_stream *xdr, attrlist4 *ptr)
{
	return xdrgen_decode_opaque(xdr, ptr, 0);
};

static bool __maybe_unused
xdrgen_decode_bitmap4(struct xdr_stream *xdr, bitmap4 *ptr)
{
	if (xdr_stream_decode_u32(xdr, &ptr->count) < 0)
		return false;
	for (u32 i = 0; i < ptr->count; i++)
		if (!xdrgen_decode_uint32_t(xdr, &ptr->element[i]))
			return false;
	return true;
};

static bool __maybe_unused
xdrgen_decode_nfs_cookie4(struct xdr_stream *xdr, nfs_cookie4 *ptr)
{
	return xdrgen_decode_uint64_t(xdr, ptr);
};

static bool __maybe_unused
xdrgen_decode_nfs_fh4(struct xdr_stream *xdr, nfs_fh4 *ptr)
{
	return xdrgen_decode_opaque(xdr, ptr, NFS4_FHSIZE);
};

static bool __maybe_unused
xdrgen_decode_utf8string(struct xdr_stream *xdr, utf8string *ptr)
{
	return xdrgen_decode_opaque(xdr, ptr, 0);
};

static bool __maybe_unused
xdrgen_decode_utf8str_cis(struct xdr_stream *xdr, utf8str_cis *ptr)
{
	return xdrgen_decode_utf8string(xdr, ptr);
};

static bool __maybe_unused
xdrgen_decode_utf8str_cs(struct xdr_stream *xdr, utf8str_cs *ptr)
{
	return xdrgen_decode_utf8string(xdr, ptr);
};

static bool __maybe_unused
xdrgen_decode_utf8str_mixed(struct xdr_stream *xdr, utf8str_mixed *ptr)
{
	return xdrgen_decode_utf8string(xdr, ptr);
};

static bool __maybe_unused
xdrgen_decode_component4(struct xdr_stream *xdr, component4 *ptr)
{
	return xdrgen_decode_utf8str_cs(xdr, ptr);
};

static bool __maybe_unused
xdrgen_decode_linktext4(struct xdr_stream *xdr, linktext4 *ptr)
{
	return xdrgen_decode_utf8str_cs(xdr, ptr);
};

static bool __maybe_unused
xdrgen_decode_pathname4(struct xdr_stream *xdr, pathname4 *ptr)
{
	if (xdr_stream_decode_u32(xdr, &ptr->count) < 0)
		return false;
	for (u32 i = 0; i < ptr->count; i++)
		if (!xdrgen_decode_component4(xdr, &ptr->element[i]))
			return false;
	return true;
};

static bool __maybe_unused
xdrgen_decode_verifier4(struct xdr_stream *xdr, verifier4 *ptr)
{
	return xdr_stream_decode_opaque_fixed(xdr, ptr, NFS4_VERIFIER_SIZE) == 0;
};

static bool __maybe_unused
xdrgen_decode_nfstime4(struct xdr_stream *xdr, struct nfstime4 *ptr)
{
	if (!xdrgen_decode_int64_t(xdr, &ptr->seconds))
		return false;
	if (!xdrgen_decode_uint32_t(xdr, &ptr->nseconds))
		return false;
	return true;
};

static bool __maybe_unused
xdrgen_decode_fattr4(struct xdr_stream *xdr, struct fattr4 *ptr)
{
	if (!xdrgen_decode_bitmap4(xdr, &ptr->attrmask))
		return false;
	if (!xdrgen_decode_attrlist4(xdr, &ptr->attr_vals))
		return false;
	return true;
};

static bool __maybe_unused
xdrgen_decode_stateid4(struct xdr_stream *xdr, struct stateid4 *ptr)
{
	if (!xdrgen_decode_uint32_t(xdr, &ptr->seqid))
		return false;
	if (xdr_stream_decode_opaque_fixed(xdr, ptr->other, 12) < 0)
		return false;
	return true;
};

static bool __maybe_unused
xdrgen_decode_fattr4_offline(struct xdr_stream *xdr, fattr4_offline *ptr)
{
	return xdrgen_decode_bool(xdr, ptr);
};

static bool __maybe_unused
xdrgen_decode_open_arguments4(struct xdr_stream *xdr, struct open_arguments4 *ptr)
{
	if (!xdrgen_decode_bitmap4(xdr, &ptr->oa_share_access))
		return false;
	if (!xdrgen_decode_bitmap4(xdr, &ptr->oa_share_deny))
		return false;
	if (!xdrgen_decode_bitmap4(xdr, &ptr->oa_share_access_want))
		return false;
	if (!xdrgen_decode_bitmap4(xdr, &ptr->oa_open_claim))
		return false;
	if (!xdrgen_decode_bitmap4(xdr, &ptr->oa_create_mode))
		return false;
	return true;
};

static bool __maybe_unused
xdrgen_decode_open_args_share_access4(struct xdr_stream *xdr, open_args_share_access4 *ptr)
{
	u32 val;

	if (xdr_stream_decode_u32(xdr, &val) < 0)
		return false;
	*ptr = val;
	return true;
}

static bool __maybe_unused
xdrgen_decode_open_args_share_deny4(struct xdr_stream *xdr, open_args_share_deny4 *ptr)
{
	u32 val;

	if (xdr_stream_decode_u32(xdr, &val) < 0)
		return false;
	*ptr = val;
	return true;
}

static bool __maybe_unused
xdrgen_decode_open_args_share_access_want4(struct xdr_stream *xdr, open_args_share_access_want4 *ptr)
{
	u32 val;

	if (xdr_stream_decode_u32(xdr, &val) < 0)
		return false;
	*ptr = val;
	return true;
}

static bool __maybe_unused
xdrgen_decode_open_args_open_claim4(struct xdr_stream *xdr, open_args_open_claim4 *ptr)
{
	u32 val;

	if (xdr_stream_decode_u32(xdr, &val) < 0)
		return false;
	*ptr = val;
	return true;
}

static bool __maybe_unused
xdrgen_decode_open_args_createmode4(struct xdr_stream *xdr, open_args_createmode4 *ptr)
{
	u32 val;

	if (xdr_stream_decode_u32(xdr, &val) < 0)
		return false;
	*ptr = val;
	return true;
}

bool
xdrgen_decode_fattr4_open_arguments(struct xdr_stream *xdr, fattr4_open_arguments *ptr)
{
	return xdrgen_decode_open_arguments4(xdr, ptr);
};

bool
xdrgen_decode_fattr4_time_deleg_access(struct xdr_stream *xdr, fattr4_time_deleg_access *ptr)
{
	return xdrgen_decode_nfstime4(xdr, ptr);
};

bool
xdrgen_decode_fattr4_time_deleg_modify(struct xdr_stream *xdr, fattr4_time_deleg_modify *ptr)
{
	return xdrgen_decode_nfstime4(xdr, ptr);
};

static bool __maybe_unused
xdrgen_decode_open_delegation_type4(struct xdr_stream *xdr, open_delegation_type4 *ptr)
{
	u32 val;

	if (xdr_stream_decode_u32(xdr, &val) < 0)
		return false;
	*ptr = val;
	return true;
}

static bool __maybe_unused
xdrgen_decode_notify_type4(struct xdr_stream *xdr, notify_type4 *ptr)
{
	u32 val;

	if (xdr_stream_decode_u32(xdr, &val) < 0)
		return false;
	*ptr = val;
	return true;
}

static bool __maybe_unused
xdrgen_decode_notify_entry4(struct xdr_stream *xdr, struct notify_entry4 *ptr)
{
	if (!xdrgen_decode_component4(xdr, &ptr->ne_file))
		return false;
	if (!xdrgen_decode_fattr4(xdr, &ptr->ne_attrs))
		return false;
	return true;
};

static bool __maybe_unused
xdrgen_decode_prev_entry4(struct xdr_stream *xdr, struct prev_entry4 *ptr)
{
	if (!xdrgen_decode_notify_entry4(xdr, &ptr->pe_prev_entry))
		return false;
	if (!xdrgen_decode_nfs_cookie4(xdr, &ptr->pe_prev_entry_cookie))
		return false;
	return true;
};

bool
xdrgen_decode_notify_remove4(struct xdr_stream *xdr, struct notify_remove4 *ptr)
{
	if (!xdrgen_decode_notify_entry4(xdr, &ptr->nrm_old_entry))
		return false;
	if (!xdrgen_decode_nfs_cookie4(xdr, &ptr->nrm_old_entry_cookie))
		return false;
	return true;
};

bool
xdrgen_decode_notify_add4(struct xdr_stream *xdr, struct notify_add4 *ptr)
{
	if (xdr_stream_decode_u32(xdr, &ptr->nad_old_entry.count) < 0)
		return false;
	if (ptr->nad_old_entry.count > 1)
		return false;
	for (u32 i = 0; i < ptr->nad_old_entry.count; i++)
		if (!xdrgen_decode_notify_remove4(xdr, &ptr->nad_old_entry.element[i]))
			return false;
	if (!xdrgen_decode_notify_entry4(xdr, &ptr->nad_new_entry))
		return false;
	if (xdr_stream_decode_u32(xdr, &ptr->nad_new_entry_cookie.count) < 0)
		return false;
	if (ptr->nad_new_entry_cookie.count > 1)
		return false;
	for (u32 i = 0; i < ptr->nad_new_entry_cookie.count; i++)
		if (!xdrgen_decode_nfs_cookie4(xdr, &ptr->nad_new_entry_cookie.element[i]))
			return false;
	if (xdr_stream_decode_u32(xdr, &ptr->nad_prev_entry.count) < 0)
		return false;
	if (ptr->nad_prev_entry.count > 1)
		return false;
	for (u32 i = 0; i < ptr->nad_prev_entry.count; i++)
		if (!xdrgen_decode_prev_entry4(xdr, &ptr->nad_prev_entry.element[i]))
			return false;
	if (!xdrgen_decode_bool(xdr, &ptr->nad_last_entry))
		return false;
	return true;
};

bool
xdrgen_decode_notify_attr4(struct xdr_stream *xdr, struct notify_attr4 *ptr)
{
	if (!xdrgen_decode_notify_entry4(xdr, &ptr->na_changed_entry))
		return false;
	return true;
};

bool
xdrgen_decode_notify_rename4(struct xdr_stream *xdr, struct notify_rename4 *ptr)
{
	if (!xdrgen_decode_notify_remove4(xdr, &ptr->nrn_old_entry))
		return false;
	if (!xdrgen_decode_notify_add4(xdr, &ptr->nrn_new_entry))
		return false;
	return true;
};

static bool __maybe_unused
xdrgen_decode_notify_verifier4(struct xdr_stream *xdr, struct notify_verifier4 *ptr)
{
	if (!xdrgen_decode_verifier4(xdr, &ptr->nv_old_cookieverf))
		return false;
	if (!xdrgen_decode_verifier4(xdr, &ptr->nv_new_cookieverf))
		return false;
	return true;
};

static bool __maybe_unused
xdrgen_decode_notifylist4(struct xdr_stream *xdr, notifylist4 *ptr)
{
	return xdrgen_decode_opaque(xdr, ptr, 0);
};

static bool __maybe_unused
xdrgen_decode_notify4(struct xdr_stream *xdr, struct notify4 *ptr)
{
	if (!xdrgen_decode_bitmap4(xdr, &ptr->notify_mask))
		return false;
	if (!xdrgen_decode_notifylist4(xdr, &ptr->notify_vals))
		return false;
	return true;
};

bool
xdrgen_decode_CB_NOTIFY4args(struct xdr_stream *xdr, struct CB_NOTIFY4args *ptr)
{
	if (!xdrgen_decode_stateid4(xdr, &ptr->cna_stateid))
		return false;
	if (!xdrgen_decode_nfs_fh4(xdr, &ptr->cna_fh))
		return false;
	if (xdr_stream_decode_u32(xdr, &ptr->cna_changes.count) < 0)
		return false;
	for (u32 i = 0; i < ptr->cna_changes.count; i++)
		if (!xdrgen_decode_notify4(xdr, &ptr->cna_changes.element[i]))
			return false;
	return true;
};

bool
xdrgen_decode_CB_NOTIFY4res(struct xdr_stream *xdr, struct CB_NOTIFY4res *ptr)
{
	if (!xdrgen_decode_nfsstat4(xdr, &ptr->cnr_status))
		return false;
	return true;
};

static bool __maybe_unused
xdrgen_encode_int32_t(struct xdr_stream *xdr, const int32_t value)
{
	return xdrgen_encode_int(xdr, value);
};

static bool __maybe_unused
xdrgen_encode_uint32_t(struct xdr_stream *xdr, const uint32_t value)
{
	return xdrgen_encode_unsigned_int(xdr, value);
};

static bool __maybe_unused
xdrgen_encode_int64_t(struct xdr_stream *xdr, const int64_t value)
{
	return xdrgen_encode_hyper(xdr, value);
};

static bool __maybe_unused
xdrgen_encode_uint64_t(struct xdr_stream *xdr, const uint64_t value)
{
	return xdrgen_encode_unsigned_hyper(xdr, value);
};

static bool __maybe_unused
xdrgen_encode_nfsstat4(struct xdr_stream *xdr, nfsstat4 value)
{
	return xdr_stream_encode_u32(xdr, value) == XDR_UNIT;
}

static bool __maybe_unused
xdrgen_encode_attrlist4(struct xdr_stream *xdr, const attrlist4 value)
{
	return xdr_stream_encode_opaque(xdr, value.data, value.len) >= 0;
};

static bool __maybe_unused
xdrgen_encode_bitmap4(struct xdr_stream *xdr, const bitmap4 value)
{
	if (xdr_stream_encode_u32(xdr, value.count) != XDR_UNIT)
		return false;
	for (u32 i = 0; i < value.count; i++)
		if (!xdrgen_encode_uint32_t(xdr, value.element[i]))
			return false;
	return true;
};

static bool __maybe_unused
xdrgen_encode_nfs_cookie4(struct xdr_stream *xdr, const nfs_cookie4 value)
{
	return xdrgen_encode_uint64_t(xdr, value);
};

static bool __maybe_unused
xdrgen_encode_nfs_fh4(struct xdr_stream *xdr, const nfs_fh4 value)
{
	return xdr_stream_encode_opaque(xdr, value.data, value.len) >= 0;
};

static bool __maybe_unused
xdrgen_encode_utf8string(struct xdr_stream *xdr, const utf8string value)
{
	return xdr_stream_encode_opaque(xdr, value.data, value.len) >= 0;
};

static bool __maybe_unused
xdrgen_encode_utf8str_cis(struct xdr_stream *xdr, const utf8str_cis value)
{
	return xdrgen_encode_utf8string(xdr, value);
};

static bool __maybe_unused
xdrgen_encode_utf8str_cs(struct xdr_stream *xdr, const utf8str_cs value)
{
	return xdrgen_encode_utf8string(xdr, value);
};

static bool __maybe_unused
xdrgen_encode_utf8str_mixed(struct xdr_stream *xdr, const utf8str_mixed value)
{
	return xdrgen_encode_utf8string(xdr, value);
};

static bool __maybe_unused
xdrgen_encode_component4(struct xdr_stream *xdr, const component4 value)
{
	return xdrgen_encode_utf8str_cs(xdr, value);
};

static bool __maybe_unused
xdrgen_encode_linktext4(struct xdr_stream *xdr, const linktext4 value)
{
	return xdrgen_encode_utf8str_cs(xdr, value);
};

static bool __maybe_unused
xdrgen_encode_pathname4(struct xdr_stream *xdr, const pathname4 value)
{
	if (xdr_stream_encode_u32(xdr, value.count) != XDR_UNIT)
		return false;
	for (u32 i = 0; i < value.count; i++)
		if (!xdrgen_encode_component4(xdr, value.element[i]))
			return false;
	return true;
};

static bool __maybe_unused
xdrgen_encode_verifier4(struct xdr_stream *xdr, const verifier4 value)
{
	return xdr_stream_encode_opaque_fixed(xdr, value, NFS4_VERIFIER_SIZE) >= 0;
};

static bool __maybe_unused
xdrgen_encode_nfstime4(struct xdr_stream *xdr, const struct nfstime4 *value)
{
	if (!xdrgen_encode_int64_t(xdr, value->seconds))
		return false;
	if (!xdrgen_encode_uint32_t(xdr, value->nseconds))
		return false;
	return true;
};

static bool __maybe_unused
xdrgen_encode_fattr4(struct xdr_stream *xdr, const struct fattr4 *value)
{
	if (!xdrgen_encode_bitmap4(xdr, value->attrmask))
		return false;
	if (!xdrgen_encode_attrlist4(xdr, value->attr_vals))
		return false;
	return true;
};

static bool __maybe_unused
xdrgen_encode_stateid4(struct xdr_stream *xdr, const struct stateid4 *value)
{
	if (!xdrgen_encode_uint32_t(xdr, value->seqid))
		return false;
	if (xdr_stream_encode_opaque_fixed(xdr, value->other, 12) < 0)
		return false;
	return true;
};

static bool __maybe_unused
xdrgen_encode_fattr4_offline(struct xdr_stream *xdr, const fattr4_offline value)
{
	return xdrgen_encode_bool(xdr, value);
};

static bool __maybe_unused
xdrgen_encode_open_arguments4(struct xdr_stream *xdr, const struct open_arguments4 *value)
{
	if (!xdrgen_encode_bitmap4(xdr, value->oa_share_access))
		return false;
	if (!xdrgen_encode_bitmap4(xdr, value->oa_share_deny))
		return false;
	if (!xdrgen_encode_bitmap4(xdr, value->oa_share_access_want))
		return false;
	if (!xdrgen_encode_bitmap4(xdr, value->oa_open_claim))
		return false;
	if (!xdrgen_encode_bitmap4(xdr, value->oa_create_mode))
		return false;
	return true;
};

static bool __maybe_unused
xdrgen_encode_open_args_share_access4(struct xdr_stream *xdr, open_args_share_access4 value)
{
	return xdr_stream_encode_u32(xdr, value) == XDR_UNIT;
}

static bool __maybe_unused
xdrgen_encode_open_args_share_deny4(struct xdr_stream *xdr, open_args_share_deny4 value)
{
	return xdr_stream_encode_u32(xdr, value) == XDR_UNIT;
}

static bool __maybe_unused
xdrgen_encode_open_args_share_access_want4(struct xdr_stream *xdr, open_args_share_access_want4 value)
{
	return xdr_stream_encode_u32(xdr, value) == XDR_UNIT;
}

static bool __maybe_unused
xdrgen_encode_open_args_open_claim4(struct xdr_stream *xdr, open_args_open_claim4 value)
{
	return xdr_stream_encode_u32(xdr, value) == XDR_UNIT;
}

static bool __maybe_unused
xdrgen_encode_open_args_createmode4(struct xdr_stream *xdr, open_args_createmode4 value)
{
	return xdr_stream_encode_u32(xdr, value) == XDR_UNIT;
}

bool
xdrgen_encode_fattr4_open_arguments(struct xdr_stream *xdr, const fattr4_open_arguments *value)
{
	return xdrgen_encode_open_arguments4(xdr, value);
};

bool
xdrgen_encode_fattr4_time_deleg_access(struct xdr_stream *xdr, const fattr4_time_deleg_access *value)
{
	return xdrgen_encode_nfstime4(xdr, value);
};

bool
xdrgen_encode_fattr4_time_deleg_modify(struct xdr_stream *xdr, const fattr4_time_deleg_modify *value)
{
	return xdrgen_encode_nfstime4(xdr, value);
};

static bool __maybe_unused
xdrgen_encode_open_delegation_type4(struct xdr_stream *xdr, open_delegation_type4 value)
{
	return xdr_stream_encode_u32(xdr, value) == XDR_UNIT;
}

static bool __maybe_unused
xdrgen_encode_notify_type4(struct xdr_stream *xdr, notify_type4 value)
{
	return xdr_stream_encode_u32(xdr, value) == XDR_UNIT;
}

static bool __maybe_unused
xdrgen_encode_notify_entry4(struct xdr_stream *xdr, const struct notify_entry4 *value)
{
	if (!xdrgen_encode_component4(xdr, value->ne_file))
		return false;
	if (!xdrgen_encode_fattr4(xdr, &value->ne_attrs))
		return false;
	return true;
};

static bool __maybe_unused
xdrgen_encode_prev_entry4(struct xdr_stream *xdr, const struct prev_entry4 *value)
{
	if (!xdrgen_encode_notify_entry4(xdr, &value->pe_prev_entry))
		return false;
	if (!xdrgen_encode_nfs_cookie4(xdr, value->pe_prev_entry_cookie))
		return false;
	return true;
};

bool
xdrgen_encode_notify_remove4(struct xdr_stream *xdr, const struct notify_remove4 *value)
{
	if (!xdrgen_encode_notify_entry4(xdr, &value->nrm_old_entry))
		return false;
	if (!xdrgen_encode_nfs_cookie4(xdr, value->nrm_old_entry_cookie))
		return false;
	return true;
};

bool
xdrgen_encode_notify_add4(struct xdr_stream *xdr, const struct notify_add4 *value)
{
	if (value->nad_old_entry.count > 1)
		return false;
	if (xdr_stream_encode_u32(xdr, value->nad_old_entry.count) != XDR_UNIT)
		return false;
	for (u32 i = 0; i < value->nad_old_entry.count; i++)
		if (!xdrgen_encode_notify_remove4(xdr, &value->nad_old_entry.element[i]))
			return false;
	if (!xdrgen_encode_notify_entry4(xdr, &value->nad_new_entry))
		return false;
	if (value->nad_new_entry_cookie.count > 1)
		return false;
	if (xdr_stream_encode_u32(xdr, value->nad_new_entry_cookie.count) != XDR_UNIT)
		return false;
	for (u32 i = 0; i < value->nad_new_entry_cookie.count; i++)
		if (!xdrgen_encode_nfs_cookie4(xdr, value->nad_new_entry_cookie.element[i]))
			return false;
	if (value->nad_prev_entry.count > 1)
		return false;
	if (xdr_stream_encode_u32(xdr, value->nad_prev_entry.count) != XDR_UNIT)
		return false;
	for (u32 i = 0; i < value->nad_prev_entry.count; i++)
		if (!xdrgen_encode_prev_entry4(xdr, &value->nad_prev_entry.element[i]))
			return false;
	if (!xdrgen_encode_bool(xdr, value->nad_last_entry))
		return false;
	return true;
};

bool
xdrgen_encode_notify_attr4(struct xdr_stream *xdr, const struct notify_attr4 *value)
{
	if (!xdrgen_encode_notify_entry4(xdr, &value->na_changed_entry))
		return false;
	return true;
};

bool
xdrgen_encode_notify_rename4(struct xdr_stream *xdr, const struct notify_rename4 *value)
{
	if (!xdrgen_encode_notify_remove4(xdr, &value->nrn_old_entry))
		return false;
	if (!xdrgen_encode_notify_add4(xdr, &value->nrn_new_entry))
		return false;
	return true;
};

static bool __maybe_unused
xdrgen_encode_notify_verifier4(struct xdr_stream *xdr, const struct notify_verifier4 *value)
{
	if (!xdrgen_encode_verifier4(xdr, value->nv_old_cookieverf))
		return false;
	if (!xdrgen_encode_verifier4(xdr, value->nv_new_cookieverf))
		return false;
	return true;
};

static bool __maybe_unused
xdrgen_encode_notifylist4(struct xdr_stream *xdr, const notifylist4 value)
{
	return xdr_stream_encode_opaque(xdr, value.data, value.len) >= 0;
};

static bool __maybe_unused
xdrgen_encode_notify4(struct xdr_stream *xdr, const struct notify4 *value)
{
	if (!xdrgen_encode_bitmap4(xdr, value->notify_mask))
		return false;
	if (!xdrgen_encode_notifylist4(xdr, value->notify_vals))
		return false;
	return true;
};

bool
xdrgen_encode_CB_NOTIFY4args(struct xdr_stream *xdr, const struct CB_NOTIFY4args *value)
{
	if (!xdrgen_encode_stateid4(xdr, &value->cna_stateid))
		return false;
	if (!xdrgen_encode_nfs_fh4(xdr, value->cna_fh))
		return false;
	if (xdr_stream_encode_u32(xdr, value->cna_changes.count) != XDR_UNIT)
		return false;
	for (u32 i = 0; i < value->cna_changes.count; i++)
		if (!xdrgen_encode_notify4(xdr, &value->cna_changes.element[i]))
			return false;
	return true;
};

bool
xdrgen_encode_CB_NOTIFY4res(struct xdr_stream *xdr, const struct CB_NOTIFY4res *value)
{
	if (!xdrgen_encode_nfsstat4(xdr, value->cnr_status))
		return false;
	return true;
};
